### ISSUE TITLE
Goal: make message from the bot sticky to the bottom of the thread

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/pr-time-tracker#283] opened 2024-07-17 14:17 UTC
Problem: currently, if you do not submit the time right away, the message can be lost as new messages from people arrive in the thread.

# Solution
Make the message from the bot always stick to the bottom of the thread (same as conventional commit Action behavior)

**Comment by bytegun** [comment] 2024-08-08 13:42
@zolotokrylin @georgeciubotaru 
I think GitHub token provided in the .npmrc is expired or invalid.
Could you provide another one?

**Comment by georgeciubotaru** [comment] 2024-08-08 15:07
@bytegun Sorry for the inconvenience. Updated the main branch code.

**Comment by bytegun** [comment] 2024-08-08 16:04
@georgeciubotaru My account should have access to the repository that hosts the @holdex/autoinvoicing package. Could you please grant me access?

Otherwise, I need the correct GHP token and will also need to log in using `npm login` with the account associated with the GitHub account that holds the GHP token.

**Comment by bytegun** [comment] 2024-08-08 16:11
```$ npm view @holdex/autoinvoicing@0.0.9
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://npm.pkg.github.com/@holdex%2fautoinvoicing - Permission permission_denied: read_package
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in: C:\Users\Santa\AppData\Local\npm-cache\_logs\2024-08-08T16_01_38_187Z-debug-0.log```

**Comment by georgeciubotaru** [comment] 2024-08-08 20:14
@bytegun try 'npm run pre-dev' and take the ghToken from end variables (NPM_RC)

**Comment by georgeciubotaru** [comment] 2024-08-12 06:24
@bytegun What is the status here?

1. Did you start working? If yes, please assign yourself.
2. If you start working don't forget about our rules for attaching the related PR

**Comment by bytegun** [comment] 2024-08-13 00:45
@georgeciubotaru I can't self assign this issue. I don't have necessary permissions to do it.
I am struggling making the github bot from this project. What webhook url should I use for the bot? https://alert-seemingly-moccasin.ngrok-free.app/api/trigger Is this URL for the webhook of the github bot?

**Comment by georgeciubotaru** [comment] 2024-08-13 06:15
@bytegun Did you manage to run the dev env?

**Comment by bytegun** [comment] 2024-08-13 12:28
@georgeciubotaru Yes, I ran the dev env. Could you please send me the invitation again? It seems the link expired.

**Comment by bytegun** [comment] 2024-08-13 12:33
Okay, got it. What is the webhook URL for the bot? https://alert-seemingly-moccasin.ngrok-free.app/api/trigger
Is it webhook URL?

**Comment by bytegun** [comment] 2024-08-16 02:41
@georgeciubotaru I found that I can't receive events other than issues, pull_request, pull_request_review, check_run
But I need to receive issue_comment event. How can I change desired events?

**Comment by georgeciubotaru** [comment] 2024-08-16 04:54
@bytegun Why do you need to parse issue_comment events?

**Comment by bytegun** [comment] 2024-08-16 05:06
@georgeciubotaru To make the bot's message sticky to the bottom, I want to get issue_comment event and delete the bot's message and write again.

**Comment by georgeciubotaru** [comment] 2024-08-16 05:15
@bytegun That bot-message happens during an action `submitting cost` so you should work on that. You don't need issue_comments parser.

**Comment by bytegun** [comment] 2024-08-16 05:17
@georgeciubotaru Yes, I know that but the goal is to move the bot's message to the bottom when a comment is added, isn't it?

**Comment by georgeciubotaru** [comment] 2024-08-16 05:18
@bytegun Please ready carefully the whole discussion on this Goal.

**Comment by teodorus-nathaniel** [comment] 2024-10-31 11:32
Hi @zolotokrylin @georgeciubotaru, I'd like to confirm my understanding of this task.

Currently, when a contributor submits the required time, the bot sends the following message:
![image](https://github.com/user-attachments/assets/db36b824-2a06-4a69-babf-d0ff6e50a40b)
However, as the conversation continues, this message gets buried under newer messages, making it less accessible.



> @zolotokrylin
> 
> Example of how to submit the cost another way: (by clicking on the `Details` link on the failed check, as we are doing with the Vercel in case the deployment failed). <img alt="image" width="936" src="https://private-user-images.githubusercontent.com/8217518/349561466-6957c6b1-1b0b-4742-aac5-c2e27fb75915.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzMwNTcsIm5iZiI6MTczMDM3Mjc1NywicGF0aCI6Ii84MjE3NTE4LzM0OTU2MTQ2Ni02OTU3YzZiMS0xYjBiLTQ3NDItYWFjNS1jMmUyN2ZiNzU5MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMTEwNTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE4NDY3YmMzYTQwYTk5NjdhZDI0ZGUyNzhjOGUwZDgwOGZmZjM5ZWRjMWZiYzkwN2YxMmNhY2NkNjg1MDA2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yAyoIsyMT2e31WjIwmRoI_THwS4qEb0KKk781JjJVWY">
> 
> Cost: 3h

So the solution is to have the bot display this message at the bottom of the chat, like the above message that @georgeciubotaru sent

Is my understanding correct?

**Comment by georgeciubotaru** [comment] 2024-10-31 11:46
Hi @teodorus-nathaniel, we displaying messages only if you didn't submit the PR cost. 
we want this message to be always the last one (in case there are commits or comments added)

Feel free to create a test PR and see yourself the entire flow

**Comment by teodorus-nathaniel** [comment] 2024-10-31 12:31
So do you mean like the message below, needs to be always the last message in the thread?
![image](https://github.com/user-attachments/assets/4e80d2d4-dc14-4466-a000-2e9d7e9663df)

And just to make sure, can I create multiple PRs for testing?

**Comment by teodorus-nathaniel** [comment] 2024-10-31 13:49
Can you that this flow fits the requirement?
In high level:
1. The bot sends the reminder to "submit the time"
2. On every `pull_request_review_comment`, it deletes the old message, and post a new one

**Comment by georgeciubotaru** [comment] 2024-10-31 14:38
@teodorus-nathaniel Please move all the comments to the related Problem (non Goal) or create one if missing.

**Comment by teodorus-nathaniel** [comment] 2024-10-31 17:58
Seems like it is related in this closed issue #205
This same method was mentioned there, so Ill do it this way for now

**Comment by markholdex** [comment] 2024-10-31 21:05
@teodorus-nathaniel Please follow the Guidelines I shared with you and create a Problem. Use that problem to address questions. However, I believe we already agreed on the outcome. I would prefer us to not give clues on the solution during the trial. Instead, it's your time to shine by implementing a solution that reflects the business requirements.

**Comment by teodorus-nathaniel** [comment] 2024-11-01 04:17
Yeah sure, it's just my habit to confirm the flow
I'm currently on progress creating the solution, the ETA is about 5 hours

**Comment by teodorus-nathaniel** [comment] 2024-11-01 07:27
Hello, the PR #306 is ready to review now

FYI, I changed a bit too in the @holdex/autoinvoicing package to enable `issue_comment` event handling, so it needs to be republished

**Comment by markholdex** [comment] 2024-11-06 10:54
Hey @teodorus-nathaniel good job so far. Reminding you about the remaining comment to complete things: 
- https://github.com/holdex/pr-time-tracker/pull/306#issuecomment-2456722113

**Comment by teodorus-nathaniel** [comment] 2024-11-06 11:35
> Hey @teodorus-nathaniel good job so far. Reminding you about the remaining comment to complete things: 
> 
> - https://github.com/holdex/pr-time-tracker/pull/306#issuecomment-2456722113

oh, that's already merged here
https://github.com/holdex/pr-time-tracker/pull/313

**Comment by markholdex** [comment] 2024-11-06 12:33
My bad @teodorus-nathaniel appreciate your reply.

**Comment by markholdex** [comment] 2024-11-06 14:47
log: implementation tested, everything is working as intended.

**Comment by zolotokrylin** [comment] 2024-11-27 16:47
![image](https://github.com/user-attachments/assets/c675cb3b-47ea-49fe-8890-0b6b9a88d8c6)

It is not sticky

**Comment by teodorus-nathaniel** [comment] 2024-11-28 05:42
> It is not sticky

Log: checking
@georgeciubotaru is it possible for you to share me access of prod trigger dev? I want to confirm whether the issue is same as what I identified for now or not

**Closed** 2024-12-09 09:04 UTC
Labels: type: goal, type: trial
